# Generated by Django 4.1.7 on 2023-05-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='img/not-avaible.png', null=True, upload_to='product'),
        ),
    ]
