# Generated by Django 4.1.7 on 2023-05-02 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedcoupon',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='usedcoupon',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='UsedCoupon',
        ),
    ]
